export declare const API_HOST: any, ActionTypes: any, LoginStates: any, FormStates: any, KeybindActions: any, KeybindCustomActions: any, RecentMentionsFilters: any, RTCDebugSections: any, GuildSettingsSections: any, ChannelSettingsSections: any, ChannelSections: any, FriendsSections: any, UserProfileSections: any, SearchSections: any, DesktopNotificationTypes: any, NotificationPermissionTypes: any, TTSNotificationTypes: any, InputModes: any, ChannelTypes: Readonly<{
    DM: number;
    GROUP_DM: number;
    GUILD_TEXT: number;
    GUILD_VOICE: number;
    GUILD_CATEGORY: number;
    GUILD_NEWS: number;
    GUILD_STORE: number;
}>, ThemeTypes: Readonly<{
    DARK: string;
    LIGHT: string;
}>, ContextMenuTypes: any, NoticeTypes: any, InviteStates: any, NativeAppStates: any, CreateGuildModalScreens: Readonly<{
    Choose: number;
    CreateGuild: number;
    JoinGuild: number;
    AcceptInvite: number;
}>, GuildFeatures: any, RTCConnectionStates: any, RTCConnectionQuality: Readonly<{
    UNKNOWN: string;
    BAD: string;
    AVERAGE: string;
    FINE: string;
}>, RTCReceivedVideoQuality: Readonly<{
    OFF: string;
    FULL: string;
}>, ExplicitContentFilterTypes: Readonly<{
    DISABLED: number;
    NON_FRIENDS: number;
    FRIENDS_AND_NON_FRIENDS: number;
}>, PageAnalyticsLocations: Readonly<{
    LOGIN: string;
    REGISTER: string;
    INVITE: string;
    VERIFY: string;
    DISABLE_EMAIL_NOTIFICATIONS: string;
    AUTHORIZE_IP: string;
    RESET: string;
    HANDOFF: string;
    UNKNOWN: string;
    LANDING: string;
}>, MessageStates: any;
export declare const MessageTypes: Readonly<{
    DEFAULT: number;
    RECIPIENT_ADD: number;
    RECIPIENT_REMOVE: number;
    CALL: number;
    CHANNEL_NAME_CHANGE: number;
    CHANNEL_ICON_CHANGE: number;
    CHANNEL_PINNED_MESSAGE: number;
    USER_JOIN: number;
}>;
export declare const MessageTypesDeletable: any, OverlayDisplayNames: any, OverlayDisplayUsers: any, OverlayWidgets: any, OverlayWidgetLayoutPolicy: any, OverlayWidgetTypes: any, OverlayAvatarSizes: Readonly<{
    LARGE: string;
    SMALL: string;
}>, OverlayNotificationTypes: any, OverlayNotificationStatus: any, OverlayNotificationPositions: Readonly<{
    TOP_LEFT: string;
    TOP_RIGHT: string;
    BOTTOM_LEFT: string;
    BOTTOM_RIGHT: string;
    DISABLED: string;
}>, OverlayNotificationTextChatTypes: any, OverlayEventTypes: any, OverlayActiveRegions: any, TextareaTypes: Readonly<{
    NORMAL: string;
    EDIT: string;
    FORM: string;
}>, VerificationLevels: Readonly<{
    NONE: number;
    LOW: number;
    MEDIUM: number;
    HIGH: number;
    VERY_HIGH: number;
}>, VerificationCriteria: Readonly<{
    ACCOUNT_AGE: number;
    MEMBER_AGE: number;
}>, MFALevels: Readonly<{
    NONE: number;
    ELEVATED: number;
}>, GuildExplicitContentFilterTypes: Readonly<{
    DISABLED: number;
    MEMBERS_WITHOUT_ROLES: number;
    ALL_MEMBERS: number;
}>, RelationshipTypes: Readonly<{
    NONE: number;
    FRIEND: number;
    BLOCKED: number;
    PENDING_INCOMING: number;
    PENDING_OUTGOING: number;
    IMPLICIT: number;
}>, DetectedPlatformAccountsDisplayTypes: any, GiftCodeModalStates: any;
export declare const Endpoints: {}, Routes: {}, RPC_SCOPE_CONFIG: Readonly<{
    ANY: string;
    ALL: string;
}>, RPC_PRIVATE_SCOPE = "RPC_PRIVATE_SCOPE", RPC_PRIVATE_LIMITED_SCOPE = "RPC_PRIVATE_LIMITED_SCOPE", RPC_LOCAL_SCOPE = "RPC_LOCAL_SCOPE", RPCDeepLinks: any, RPCErrors: Readonly<{
    UNKNOWN_ERROR: number;
    SERVICE_UNAVAILABLE: number;
    TRANSACTION_ABORTED: number;
    INVALID_PAYLOAD: number;
    INVALID_COMMAND: number;
    INVALID_GUILD: number;
    INVALID_EVENT: number;
    INVALID_CHANNEL: number;
    INVALID_PERMISSIONS: number;
    INVALID_CLIENTID: number;
    INVALID_ORIGIN: number;
    INVALID_TOKEN: number;
    INVALID_USER: number;
    INVALID_INVITE: number;
    INVALID_ACTIVITY_JOIN_REQUEST: number;
    INVALID_LOBBY: number;
    INVALID_LOBBY_SECRET: number;
    INVALID_ENTITLEMENT: number;
    INVALID_GIFT_CODE: number;
    OAUTH2_ERROR: number;
    SELECT_CHANNEL_TIMED_OUT: number;
    GET_GUILD_TIMED_OUT: number;
    SELECT_VOICE_FORCE_REQUIRED: number;
    CAPTURE_SHORTCUT_ALREADY_LISTENING: number;
    INVALID_ACTIVITY_SECRET: number;
    NO_ELIGIBLE_ACTIVITY: number;
    LOBBY_FULL: number;
    PURCHASE_CANCELED: number;
    PURCHASE_ERROR: number;
    UNAUTHORIZED_FOR_ACHIEVEMENT: number;
    RATE_LIMITED: number;
}>, DispatchErrorCodes: Readonly<{
    APPLICATION_NOT_FOUND: number;
    DISK_LOW: number;
    DISK_PERMISSION_DENIED: number;
    POST_INSTALL_FAILED: number;
    REDISTRIBUTABLE_INSTALL_FAILED: number;
    APPLICATION_LOAD_FAILED: number;
    DESERIALIZATION_FAILED: number;
    INTERRUPTED: number;
    MAX_REQUEST_RETRIES_EXCEEDED: number;
    AUTHENTICATION_FAILED: number;
    IO_PERMISSION_DENIED: number;
    NO_MANIFESTS: number;
    POST_INSTALL_CANCELLED: number;
    API_ERROR: number;
    FILE_NAME_TOO_LONG: number;
    NOT_ENTITLED: number;
    APPLICATION_LOCK_FAILED: number;
    NOT_DIRECTORY: number;
    INVALID_DRIVE: number;
    DISK_FULL: number;
}>, GameLaunchStatuses: Readonly<{
    LAUNCH_TARGET_NOT_FOUND: number;
}>, TransportTypes: Readonly<{
    IPC: string;
    WEBSOCKET: string;
    HTTP: string;
}>, ActivityFlags: Readonly<{
    INSTANCE: number;
    JOIN: number;
    SPECTATE: number;
    SYNC: number;
    PLAY: number;
}>, UserNotificationSettings: Readonly<{
    ALL_MESSAGES: number;
    ONLY_MENTIONS: number;
    NO_MESSAGES: number;
    NULL: number;
}>;
export declare const ME = "@me", MAX_MESSAGES_PER_CHANNEL = 50, MAX_MENTIONS_PER_FETCH = 25, MAX_LOADED_MESSAGES: number, TRUNCATED_MESSAGE_VIEW_SIZE: number, MAX_MESSAGE_CACHE_SIZE: number, MAX_MESSAGE_LENGTH = 2000, MAX_TTS_LENGTH = 200, MAX_PINS_PER_CHANNEL = 50, IDLE_DURATION = 600000, TYPING_TIMEOUT = 10000, MAX_TYPING_USERS = 5, SLOWMODE_COOLDOWN_BUFFER_MS = 100, SLOWMODE_VALUES: number[], MAX_ROLE_LENGTH = 32, MAX_ATTACHMENT_SIZE = 8388608, MAX_PREMIUM_ATTACHMENT_SIZE = 52428800, EMBED_LIFETIME = 7200000, GAME_REPORT_VERSION = 3, MAX_GAMES_NEWS = 100, SPOILER_ATTACHMENT_PREFIX = "SPOILER_", MARKDOWN_SPOILER_WRAPPER: (e: any) => string, MARKDOWN_SPOILER_REGEXP: RegExp, MARKDOWN_SPOILER_REGEXP_GLOBAL: RegExp, ChannelStreamTypes: any, ChannelModes: Readonly<{
    VIDEO: string;
    VOICE: string;
}>, ActivityTypes: Readonly<{
    PLAYING: number;
    STREAMING: number;
    LISTENING: number;
    WATCHING: number;
}>, ActivityActionTypes: Readonly<{
    JOIN: number;
    SPECTATE: number;
    LISTEN: number;
    WATCH: number;
    JOIN_REQUEST: number;
}>;
export declare const ActivityCardTypes: Readonly<{
    GAME: string;
    USER: string;
    GROUP: string;
}>, ActivityActionStates: any, AVATAR_SIZE = 128, AVATAR_MAX_SIZE = 1024, SPLASH_SIZE = 2048, ACTIVITY_INVITE_COVER_IMAGE_SIZE = 160, MAX_PTT_RELEASE_DELAY = 2000, EMOJI_CATEGORY_RECENT = "recent", EMOJI_CATEGORY_CUSTOM = "custom", BITRATE_MIN = 8000, BITRATE_DEFAULT = 64000, BITRATE_MAX = 96000, BITRATE_MAX_VIP = 128000, NON_USER_BOT_DISCRIMINATOR = "0000", LOCAL_BOT_ID = "1", MAX_VOICE_USER_LIMIT = 99, MAX_MUTUAL_GUILDS = 5, MAX_GROUP_DM_PARTICIPANTS = 10, PLACEHOLDER_TAG = "#0000", LEFT_PANEL_WIDTH = 320, DEVICE_TOKEN = "DEVICE_TOKEN", DEVICE_PUSH_PROVIDER: any, FIRST_RUN_DATE_KEY = "first_run_date_key", MarketingURLs: Readonly<{
    API_DOCS: string;
    API_DOCS_GAME_AND_SERVER_MANAGEMENT: string;
    API_DOCS_APPLICATION_SKUS_INDEX: (e: any) => string;
    API_DOCS_NEWS_CHANNELS: string;
    COMPANY: string;
    PARTNERS: string;
    HYPESQUAD: string;
    TERMS: string;
    PRIVACY: string;
    GUIDELINES: string;
    ACKNOWLEDGEMENTS: string;
    DOWNLOAD: string;
}>, TWITCH_CLIENT_ID = "33kozedd0zs6fbauka98psnc7zwom2s", MAX_AUTOCOMPLETE_RESULTS = 10, LARGE_SERVER_MEMBER_THRESHOLD = 100, SEARCH_PAGE_SIZE = 25, IS_SEARCH_FILTER_TOKEN: RegExp, IS_SEARCH_ANSWER_TOKEN: RegExp, EMOJI_MAX_SLOTS = 50, EMOJI_MAX_SLOTS_MORE = 200, EMOJI_MAX_LENGTH = 32, EMOJI_RE: RegExp, EMOJI_MAX_FILESIZE_KB = 256, SearchTypes: any, SearchModes: Readonly<{
    RECENT: string;
    RELEVANT: string;
}>, EmojiSprites: Readonly<{
    NonDiversityPerRow: number;
    DiversityPerRow: number;
    PickerPerRow: number;
    PickerCount: number;
}>, DIVERSITY_SURROGATES: string[], AbortCodes: Readonly<{
    UNKNOWN_ACCOUNT: number;
    UNKNOWN_APPLICATION: number;
    UNKNOWN_CHANNEL: number;
    UNKNOWN_GUILD: number;
    UNKNOWN_INTEGRATION: number;
    UNKNOWN_INVITE: number;
    UNKNOWN_MEMBER: number;
    UNKNOWN_MESSAGE: number;
    UNKNOWN_OVERWRITE: number;
    UNKNOWN_PLATFORM: number;
    UNKNOWN_ROLE: number;
    UNKNOWN_TOKEN: number;
    UNKNOWN_USER: number;
    UNKNOWN_EMOJI: number;
    UNKNOWN_WEBHOOK: number;
    UNKNOWN_GIFT_CODE: number;
    BOT_DISALLOWED: number;
    BOT_REQUIRED: number;
    RPC_PROXY_DISALLOWED: number;
    EXPLICIT_CONTENT: number;
    ACCOUNT_SCHEDULED_FOR_DELETION: number;
    USER_NOT_AUTHORIZED_FOR_APPLICATION: number;
    ACCOUNT_DISABLED: number;
    SLOWMODE_RATE_LIMITED: number;
    TOO_MANY_USER_GUILDS: number;
    TOO_MANY_BOT_GUILDS: number;
    TOO_MANY_FRIENDS: number;
    TOO_MANY_PINS_IN_CHANNEL: number;
    TOO_MANY_RECIPIENTS: number;
    TOO_MANY_GUILD_ROLES: number;
    TOO_MANY_USING_USERNAME: number;
    TOO_MANY_WEBHOOKS: number;
    TOO_MANY_EMOJI: number;
    TOO_MANY_REACTIONS: number;
    TOO_MANY_ANIMATED_EMOJI: number;
    UNAUTHORIZED: number;
    EMAIL_VERIFICATION_REQUIRED: number;
    RATE_LIMIT_DM_OPEN: number;
    SEND_MESSAGE_TEMPORARILY_DISABLED: number;
    DELETE_ACCOUNT_TRANSFER_TEAM_OWNERSHIP: number;
    INVALID_ACCESS: number;
    INVALID_ACCOUNT_TYPE: number;
    INVALID_ACTION_DM: number;
    INVALID_EMBED_DISABLED: number;
    INVALID_MESSAGE_AUTHOR: number;
    INVALID_MESSAGE_EMPTY: number;
    INVALID_MESSAGE_SEND_USER: number;
    INVALID_MESSAGE_SEND_NON_TEXT: number;
    INVALID_MESSAGE_VERIFICATION_LEVEL: number;
    INVALID_OAUTH_APP_BOT: number;
    INVALID_OAUTH_APP_LIMIT: number;
    INVALID_OAUTH_STATE: number;
    INVALID_PERMISSIONS: number;
    INVALID_TOKEN: number;
    INVALID_NOTE: number;
    INVALID_BULK_DELETE_COUNT: number;
    INVALID_MFA_LEVEL: number;
    INVALID_PASSWORD: number;
    INVALID_PIN_MESSAGE_CHANNEL: number;
    INVALID_INVITE_CODE: number;
    INVALID_PHONE_NUMBER: number;
    INVALID_CLIENT_ID: number;
    INVALID_CHANNEL_TYPE: number;
    INVALID_OAUTH2_ACCESS_TOKEN: number;
    INVALID_OAUTH2_MISSING_SCOPE: number;
    INVALID_WEBHOOK_TOKEN: number;
    INVALID_GIFT_REDEMPTION_EXHAUSTED: number;
    INVALID_GIFT_REDEMPTION_OWNED: number;
    INVALID_GIFT_SELF_REDEMPTION: number;
    INVALID_GIFT_REDEMPTION_SUBSCRIPTION_MANAGED: number;
    INVALID_GIFT_REDEMPTION_SUBSCRIPTION_INCOMPATIBLE: number;
    INVALID_GIFT_REDEMPTION_INVOICE_OPEN: number;
    MFA_ENABLED: number;
    MFA_DISABLED: number;
    MFA_REQUIRED: number;
    MFA_UNVERIFIED: number;
    MFA_INVALID_SECRET: number;
    MFA_INVALID_TICKET: number;
    MFA_INVALID_CODE: number;
    MFA_INVALID_SESSION: number;
    PHONE_NUMBER_UNABLE_TO_SEND: number;
    RELATIONSHIP_INCOMING_DISABLED: number;
    RELATIONSHIP_INCOMING_BLOCKED: number;
    RELATIONSHIP_INVALUD_USER_BOT: number;
    RELATIONSHIP_INVALID_SELF: number;
    RELATIONSHIP_INVALID_DISCORD_TAG: number;
    REACTION_BLOCKED: number;
    LISTING_ALREADY_JOINED: number;
    LISTING_TOO_MANY_MEMBERS: number;
    LISTING_JOIN_BLOCKED: number;
}>;
export declare const CLYDE_ERROR_MESSAGES: any, ExperimentBuckets: Readonly<{
    NOT_ELIGIBLE: number;
    CONTROL: number;
    TREATMENT_1: number;
    TREATMENT_2: number;
    TREATMENT_3: number;
    TREATMENT_4: number;
    TREATMENT_5: number;
    TREATMENT_6: number;
    TREATMENT_7: number;
}>, ExperimentTypes: Readonly<{
    GUILD: string;
    USER: string;
    DEVELOPER: string;
    NONE: string;
}>, ExperimentContextTypes: Readonly<{
    GUILD: string;
    CHANNEL: string;
}>, ExperimentLocationContextTypes: any, Experiments: Readonly<{
    MOBILE_SURVEY: string;
    CHAT_CLAIM_MODAL: string;
    MOBILE_INVITE: string;
    HOMEPAGE_NUF: string;
    GUILD_VIDEO: string;
    EXPERIMENTAL_ADM: string;
    REDESIGNED_NUF: string;
    AUDIO_ISSUE_NOTICE_MIC_TESTER: string;
    AUDIO_ISSUE_NOTICE_MIC_TESTER_WEB: string;
    REDESIGNED_ADD_GUILD: string;
    STORE_DIRECTORY_BUY_INLINE: string;
    TUTORIAL_LOGIC: string;
    APPLICATION_LIBRARY_PREMIUM: string;
    TUTORIAL_UI: string;
    MOBILE_INVITE_CONTACTS: string;
    SPOILER_TAGS: string;
    GIF_PICKER: string;
    AF_NEWS_CAROUSEL: string;
    PERSONALIZED_CONTENT_NOTICE: string;
    PREMIUM_TRIAL: string;
    SERVER_DISCOVERY: string;
    MOBILE_NUF_CREATE_SERVER: string;
    MOBILE_NUF_WELCOME: string;
    ACTIVITY_FEED_REHAUL: string;
    STORE_DIRECTORY_LAYOUT: string;
    SURVEY_NITRO: string;
    SYSTEM_SURVEY: string;
    GUEST_LURKER_MODE: string;
    AF2_PROMOTION: string;
    HYPESQUAD_KOH_WINNER_BADGES: string;
    IOS_NITRO: string;
}>, AnalyticsLocations: Readonly<{
    GUILD_CREATE_INVITE_SUGGESTION: string;
    ACTIVITY_FEED: string;
    CAROUSEL_PROMOTION_UNIT: string;
    MESSAGE_EMBED: string;
    GAME_POPOUT: string;
    GAME_MODAL: string;
    PROFILE_POPOUT: string;
    QUICK_LAUNCHER: string;
    TRAY_CONTEXT_MENU: string;
    QUICK_SWITCHER: string;
    APPLICATION_LIBRARY: string;
    APPLICATION_LIBRARY_UPDATES: string;
    APPLICATION_STORE: string;
    APPLICATION_STORE_HEADER: string;
    APPLICATION_STORE_TILE: string;
    APPLICATION_STORE_HERO: string;
    APPLICATION_STORE_PAYMENT_MODAL: string;
    APPLICATION_STORE_LISTING_BACK_BUTTON: string;
    APPLICATION_STORE_LISTING_DETAILS: string;
    APPLICATION_STORE_RELATED_CONTENT: string;
    APPLICATION_STORE_PREMIUM_CAROUSEL: string;
    APPLICATION_STORE_WARNING: string;
    APPLICATION_CONTEXT_MENU_TOGGLE_INSTALL: string;
    APPLICATION_CONTEXT_MENU_PLAY: string;
    APPLICATION_TEST_MODE_NOTICE: string;
    HOME_BUTTON: string;
    HOME_NAVIGATION: string;
    IN_APPLICATION_PURCHASE_OVERLAY: string;
    IN_APPLICATION_PURCHASE_FALLBACK: string;
    URI_SCHEME: string;
    CREATE_JOIN_GUILD_MODAL: string;
    LOCKED_OVERLAY: string;
    UNLOCKED_OVERLAY: string;
    PROMOTION_CARD: string;
    SHARE_NEWS_MODAL: string;
}>, AnalyticsGameOpenTypes: Readonly<{
    SPECTATE: string;
    JOIN: string;
    ASK_TO_JOIN: string;
    LAUNCH: string;
}>, AnalyticsGamePlatforms: Readonly<{
    DESKTOP: string;
    XBOX: string;
}>, AnalyticsUserStatusTypes: Readonly<{
    ONLINE_DESKTOP: string;
    ONLINE_MOBILE: string;
}>, AnalyticsOverlayLocations: Readonly<{
    OVERLAY_UNLOCKED: string;
    OVERLAY_UNLOCKED_PINNED: string;
    OVERLAY_LOCKED_ACTIVATED: string;
}>, AnalyticsPages: Readonly<{
    STORE_LISTING: string;
    STORE_DIRECTORY_HOME: string;
    STORE_DIRECTORY_BROWSE: string;
    CHANNEL_STORE_LISTING: string;
    LIBRARY: string;
    LIBRARY_PREMIUM_APPLICATIONS: string;
    LIBRARY_INVENTORY: string;
    USER_SETTINGS: string;
    ACTIVITY_FEED: string;
    GUILD_CHANNEL: string;
    DM_CHANNEL: string;
    FRIENDS_LIST: string;
    DIRECT: string;
    IN_APP: string;
}>;
export declare const AnalyticsSections: Readonly<{
    HERO: string;
    BODY: string;
    NAVIGATION: string;
    TABS: string;
    NOTIFICATION_BAR: string;
    PROFILE_MODAL: string;
    EMOJI_PICKER_POPOUT: string;
    FILE_UPLOAD_POPOUT: string;
    PROFILE_POPOUT: string;
    SCREENSHARE_POPOUT: string;
    GAME_MODAL: string;
    GAME_POPOUT: string;
    IOS_TWO_FA_MODAL: string;
    IOS_TWO_FA_LANDING: string;
    IOS_TWO_FA_SCAN: string;
    IOS_TWO_FA_ENTER_CODE: string;
    IOS_TWO_FA_SUCCESS: string;
    IOS_TWO_FA_ADD_SMS: string;
    IOS_TWO_FA_VERIFY_SMS: string;
    CHANNEL_TEXT_AREA: string;
    ACTIVITY_FEED_QUICK_LAUNCHER: string;
    ACTIVITY_FEED_FEED: string;
    ACTIVITY_FEED_GAME_POPOUT: string;
    ACTIVITY_FEED_NOW_PLAYING: string;
    ACTIVITY_FEED_RECENTLY_PLAYED: string;
    ACTIVITY_FEED_NOW_PLAYING_HOVER_POPOUT: string;
    ACTIVITY_FEED_RECENTLY_PLAYED_HOVER_POPOUT: string;
    ACTIVITY_FEED_2_FEED: string;
    ACTIVITY_FEED_2_SIDE_BAR: string;
    LIBRARY_INSTALL_MODULE: string;
    LIBRARY_APPLICATION_LIST: string;
    LIBRARY_PREMIUM_APPLICATIONS: string;
    LIBRARY_GAME_MODAL: string;
    LIBRARY_INVENTORY_CODE_REDEMPTION: string;
    LIBRARY_INVENTORY_GIFTS_LIST: string;
    STORE_LISTING_BUY_GAME: string;
    STORE_LISTING_BUY: string;
    SETTINGS_ACCOUNT: string;
    SETTINGS_EDIT_ACCOUNT: string;
    SETTINGS_CHANGE_PASSWORD: string;
    SETTINGS_BACKUP_CODES: string;
    SETTINGS_PRIVACY_AND_SAFETY: string;
    SETTINGS_AUTHORIZED_APPS: string;
    SETTINGS_CONNECTIONS: string;
    SETTINGS_CONNECTIONS_XBOX: string;
    SETTINGS_BILLING: string;
    SETTINGS_PREMIUM: string;
    SETTINGS_HYPESQUAD_ONLINE: string;
    SETTINGS_VOICE_AND_VIDEO: string;
    SETTINGS_OVERLAY: string;
    SETTINGS_NOTIFICATIONS: string;
    SETTINGS_KEYBINDS: string;
    SETTINGS_GAME_ACTIVITY: string;
    SETTINGS_GAME_LIBRARY: string;
    SETTINGS_TEXT_AND_IMAGES: string;
    SETTINGS_APPEARANCE: string;
    SETTINGS_STREAMER_MODE: string;
    SETTINGS_LANGUAGE: string;
    SETTINGS_CHANGELOG: string;
    SETTINGS_EXPERIMENTS: string;
    SETTINGS_DEVELOPER_OPTIONS: string;
    SETTINGS_WINDOWS: string;
    SETTINGS_LINUX: string;
    SETTINGS_ACTIVITY_FEED: string;
    SETTINGS_BROWSER: string;
    SETTINGS_OVERVIEW: string;
    APPLICATION_EMBED: string;
    GIFT_CODE_EMBED: string;
}>;
export declare const AnalyticsObjects: Readonly<{
    TOOLTIP: string;
    CARD: string;
    CAROUSEL: string;
    NAVIGATION_LINK: string;
    BUTTON_BROWSE: string;
    BUTTON_HOME: string;
    BUTTON_BACK: string;
    BUTTON_CTA: string;
    BUTTON_ICON: string;
    MENU_LINK: string;
    WEB_URL: string;
    LIST_ITEM: string;
    CONTEXT_MENU: string;
    SEARCH: string;
    ALTERNATIVE_SKU: string;
    HOVER_MENU: string;
    AVATAR: string;
}>;
export declare const AnalyticsObjectTypes: Readonly<{
    GIFT: string;
    BUY: string;
    BOX_ART: string;
    PERK: string;
}>, DIRECT_ANALYTICS_LOCATION: {
    page: any;
    object: any;
}, UserSettingsSections: Readonly<{
    OVERVIEW: any;
    BROWSER: any;
    CHANGE_LOG: any;
    ACCOUNT: any;
    ACCOUNT_EDIT: any;
    ACCOUNT_CHANGE_PASSWORD: any;
    ACCOUNT_BACKUP_CODES: any;
    CONNECTIONS: any;
    CONNECTIONS_XBOX: any;
    AUTHORIZED_APPS: any;
    TEXT: any;
    VOICE: any;
    PRIVACY_AND_SAFETY: any;
    NOTIFICATIONS: any;
    GAME_ACTIVITY: any;
    GAME_LIBRARY: any;
    KEYBINDS: any;
    APPEARANCE: any;
    OVERLAY: any;
    LOCALE: any;
    STREAMER_MODE: any;
    PREMIUM: any;
    BILLING: any;
    EXPERIMENTS: any;
    DEVELOPER_OPTIONS: any;
    WINDOWS: any;
    LINUX: any;
    HYPESQUAD_ONLINE: any;
    ACTIVITY_FEED: any;
}>, TwoFAModalSetupSections: Readonly<{
    LANDING: any;
    SCAN: any;
    ENTER_CODE: any;
    SUCCESS: any;
    ADD_SMS: any;
    VERIFY_SMS: any;
}>, PopoutCallers: any, InstantInviteSources: Readonly<{
    INVITE_NOTICE: string;
    SETTINGS_INVITE: string;
    CONTEXT_MENU: string;
    WELCOME_MESSAGE: string;
    GUILD_CHANNELS: string;
    GUILD_HEADER: string;
    GUILD_CONTEXT_MENU: string;
    GUILD_CREATE: string;
}>, ComponentActions: Readonly<{
    MODAL_SUBMIT: string;
    MODAL_CLOSE: string;
    TEXTAREA_FOCUS: string;
    TEXTAREA_BLUR: string;
    SCROLLTO_PRESENT: string;
    SCROLLTO_CHANNEL: string;
    TOGGLE_CHANNEL_PINS: string;
    TOGGLE_MENTIONS: string;
    TOGGLE_EMOJI_POPOUT: string;
    TOGGLE_GIF_PICKER_POPOUT: string;
    TOGGLE_DM_CREATE: string;
    INSERT_TEXT: string;
    SCROLL_PAGE_DOWN: string;
    SCROLL_PAGE_UP: string;
    FOCUS_FRIEND_SEARCH: string;
    BLUR_INPUT: string;
    POPOUT_CLOSE: string;
    UPLOAD_FILE: string;
    CALL_ACCEPT: string;
    CALL_DECLINE: string;
    CALL_START: string;
    DDR_ARROW_DOWN: string;
    DDR_ARROW_UP: string;
    SHAKE_APP: string;
    EMPHASIZE_NOTICE: string;
    EMPHASIZE_SLOWMODE_COOLDOWN: string;
    TOGGLE_REACTION_POPOUT: (e: any) => string;
    SET_SEARCH_QUERY: string;
    FOCUS_SEARCH: string;
    PERFORM_SEARCH: string;
    QUICKSWITCHER_RESULT_FOCUS: string;
    LAYER_POP_ESCAPE_KEY: string;
    LAYER_POP_COMPLETE: string;
    CONTEXT_MENU_CLOSE: string;
    GUILD_SIDEBAR_FORCE_UPDATE: string;
    WAVE_EMPHASIZE: string;
    CHAT_RESIZE: string;
    CAROUSEL_NEXT: string;
    CAROUSEL_PREV: string;
    MODAL_CAROUSEL_NEXT: string;
    MODAL_CAROUSEL_PREV: string;
    STORE_VIDEO_PLAY: string;
    OVERLAY_GUILD_RESIZE: string;
    TRANSITION_JOIN_GUILD: string;
    TOGGLE_GIF_PICKER: string;
    CLOSE_GIF_PICKER: string;
    FAVORITE_GIF: string;
}>, NAVIGATION_THROTTLE = 50, PlatformTypes: Readonly<{
    TWITCH: string;
    YOUTUBE: string;
    SKYPE: string;
    STEAM: string;
    LEAGUE_OF_LEGENDS: string;
    BATTLENET: string;
    REDDIT: string;
    TWITTER: string;
    SPOTIFY: string;
    FACEBOOK: string;
    XBOX: string;
}>;
export declare const UNSAFE_PLATFORM_TYPES: Set<any>;
export declare const SAFE_PLATFORM_TYPES: Set<any>, FRIEND_SYNC_PLATFORM_TYPES: Set<any>, ACTIVITY_PLATFORM_TYPES: Set<any>, Arrows: any, SurveyUrls: Readonly<{
    PLATFORM: string;
    COMMUNITIES: string;
    MOBILE: (e: any) => string;
}>, AppSuccessTypes: Readonly<{
    CANCEL: string;
    NITRO: string;
    PAYMENT_SOURCE: string;
    UNKNOWN: string;
}>, DownloadLinks: Readonly<{
    DESKTOP: string;
    IOS: string;
    ANDROID: string;
    DYNAMIC: (e: any) => string;
    DYNAMIC_LINK: (e: any, t: any) => string;
}>, DEFAULT_ROLE_COLOR = 10070709, ROLE_COLORS: number[], PermissionOverrideType: any, NativeFeatures: Readonly<{
    VOICE_LEGACY_SUBSYSTEM: string;
    DEBUG_LOGGING: string;
}>, SearchTokenTypes: any, SearchAutocompleteGroups: any, SearchPopoutModes: any, SEARCH_DATE_FORMAT = "YYYY-MM-DD", SEARCH_MONTH_FORMAT = "MMMM", SEARCH_POPOUT_ID = "search-popout", NEW_GROUP_DM_POPOUT_ID = "PrivateChannelRecipientsInvitePopout", PremiumTypes: Readonly<{
    NONE: number;
    TIER_1: number;
    TIER_2: number;
}>;
export declare const PREMIUM_SUBSCRIPTION_APPLICATION = "521842831262875670", PremiumSubscriptionSKUs: Readonly<{
    LEGACY: string;
    TIER_1: string;
    TIER_2: string;
}>;
export declare const PremiumSubscriptionSKUToPremiumType: any, SubscriptionPlans: Readonly<{
    PREMIUM_MONTH_LEGACY: string;
    PREMIUM_YEAR_LEGACY: string;
    PREMIUM_MONTH_TIER_1: string;
    PREMIUM_YEAR_TIER_1: string;
    PREMIUM_MONTH_TIER_2: string;
    PREMIUM_YEAR_TIER_2: string;
}>;
export declare const IAP_PAYMENT_GATEWAY_PLAN_IDS: any[], PREMIUM_PLANS: Set<any>, SubscriptionIntervalTypes: Readonly<{
    MONTH: number;
    YEAR: number;
    DAY: number;
}>;
export declare const SubscriptionPlanInfo: any, PREMIUM_SUBSCRIPTION_TRIAL_ID = "520373071933079552";
export declare const SubscriptionTrials: any, PaymentFlags: Readonly<{
    GIFT: number;
    PREORDER: number;
}>, SubscriptionStatusTypes: Readonly<{
    UNPAID: number;
    ACTIVE: number;
    PAST_DUE: number;
    CANCELED: number;
}>, PremiumPaymentSubscriptionModes: Readonly<{
    NEW: string;
    RESUBSCRIBE: string;
}>, PaymentModalSteps: Readonly<{
    SELECT: number;
    CREDIT_CARD: number;
    PAYPAL: number;
    PAYPAL_CONFIRM: number;
    COMPLETING: number;
}>, SubscriptionTypes: Readonly<{
    PREMIUM: number;
}>, PaymentModalPriceChangedError = "Price changed", MAX_IMAGE_WIDTH = 2560, MAX_IMAGE_HEIGHT = 2560, AutocompleterResultTypes: any, AutoCompleteResultTypes: any, Accessibility: Readonly<{
    FONT_SCALE_DEFAULT: number;
    FONT_SCALE_MIN: number;
    FONT_SCALE_MAX: number;
    FONT_SCALES: number[];
    ZOOM_DEFAULT: number;
    ZOOM_MIN: number;
    ZOOM_MAX: number;
    ZOOM_SCALES: number[];
}>, INVITE_BANNER_MEMBER_THRESHOLD = 1, AnalyticEvents: Readonly<{
    APP_OPENED: string;
    APP_UI_VIEWED: string;
    APP_LAUNCH_COMPLETED: string;
    APP_LANDING_VIEWED: string;
    REGISTER_VIEWED: string;
    LOGIN_VIEWED: string;
    EXTERNAL_FINGERPRINT_DROPPED: string;
    EXTERNAL_DYNAMIC_LINK_RECEIVED: string;
    INVITE_OPENED: string;
    INVITE_VIEWED: string;
    INVITE_RESOLVED: string;
    INVITE_APP_INVOKED: string;
    INVITE_APP_OPENED: string;
    INVITE_LEARN_MORE: string;
    INVITE_LOGIN: string;
    INVITE_LOGIN_SUCCESSFUL: string;
    INSTANT_INVITE_SHARED: string;
    COPY_INSTANT_INVITE: string;
    VERIFY_ACCOUNT_APP_OPENED: string;
    QUICKSWITCHER_OPENED: string;
    QUICKSWITCHER_CLOSED: string;
    QUICKSWITCHER_RESULT_SELECTED: string;
    ENABLE_NOTIFICATIONS: string;
    NOTIFICATION_CLICKED: string;
    NOTIFICATION_VIEWED: string;
    ACK_MESSAGES: string;
    VOICE_CHANNEL_SELECTED: string;
    JOIN_VOICE_CHANNEL: string;
    LEAVE_VOICE_CHANNEL: string;
    VOICE_CONNECTION_FAILURE: string;
    VOICE_CONNECTION_SUCCESS: string;
    VOICE_DISCONNECT: string;
    START_SPEAKING: string;
    START_LISTENING: string;
    MEMBER_LIST_VIEWED: string;
    DM_LIST_VIEWED: string;
    SETTINGS_PANE_VIEWED: string;
    CHANNEL_NOTICE_VIEWED: string;
    CHANNEL_NOTICE_CLOSED: string;
    PREMIUM_PROMOTION_OPENED: string;
    PERMISSIONS_REQUESTED: string;
    PERMISSIONS_ACKED: string;
    LOCAL_SETTINGS_UPDATED: string;
    APP_NOTICE_VIEWED: string;
    APP_NOTICE_CLOSED: string;
    VIDEO_LAYOUT_TOGGLED: string;
    VIDEO_INPUT_TOGGLED: string;
    AUTHORIZED_APP_CONNECTED: string;
    OPEN_MODAL: string;
    OPEN_POPOUT: string;
    MODAL_DISMISSED: string;
    HOVER_MENU_OPENED: string;
    CREATE_GUILD_VIEWED: string;
    JOIN_GUILD_VIEWED: string;
    ACTIVITY_FEED_VIEWED: string;
    ACTIVITY_FEED_LOADED: string;
    ACTIVITY_FEED_EXITED: string;
    ACTIVITY_FEED_CUSTOMIZATION_OPENED: string;
    ACTIVITY_FEED_CUSTOMIZATION_SAVED: string;
    ACTIVITY_FEED_VOICE_CHANNEL_VISITED: string;
    ACTIVITY_FEED_GUILD_VISITED: string;
    ACTIVITY_FEED_DM_VISITED: string;
    ACTIVITY_FEED_USER_POPOUT_OPENED: string;
    ACTIVITY_FEED_GAME_POPOUT_OPENED: string;
    GAME_NEWS_CHANGED: string;
    GAME_NEWS_OPENED: string;
    APPLICATION_OPENED: string;
    LAUNCH_GAME: string;
    ACTIVITY_UPDATED: string;
    BROWSER_HANDOFF_SUCCEEDED: string;
    SHOW_TUTORIAL: string;
    CLOSE_TUTORIAL: string;
    DISMISS_ALL_TUTORIALS: string;
    INVITE_SENT: string;
    HOOK_RESULT: string;
    OVERLAY_TOGGLED: string;
    OVERLAY_HOOK_RESULT: string;
    OVERLAY_INITIALIZED: string;
    OVERLAY_LOCKED: string;
    OVERLAY_UNLOCKED: string;
    OVERLAY_PIN_TOGGLED: string;
    OVERLAY_LAYOUT_UPDATED: string;
    OVERLAY_SETTINGS_UPDATED: string;
    SPOTIFY_AUTO_PAUSED: string;
    SPOTIFY_BUTTON_CLICKED: string;
    SPOTIFY_LISTEN_ALONG_STARTED: string;
    SPOTIFY_LISTEN_ALONG_ENDED: string;
    INVITE_SUGGESTION_OPENED: string;
    GUILD_VIEWED: string;
    FRIENDS_LIST_VIEWED: string;
    CONNECTED_ACCOUNT_INITIATED: string;
    DOWNLOAD_APP: string;
    PAYMENT_FLOW_STARTED: string;
    PAYMENT_FLOW_COMPLETED: string;
    PAYMENT_FLOW_STEP: string;
    PAYMENT_FLOW_FAILED: string;
    PREMIUM_UPGRADE_STARTED: string;
    CHANNEL_MEMBER_KICKED: string;
    CHANNEL_OPENED: string;
    NUO_TRANSITION_KEY: string;
    NUO_GUILD_DATA: string;
    SOUNDSHARE_ATTACHED: string;
    SOUNDSHARE_TRANSMITTING: string;
    VIDEOHOOK_INITIALIZED: string;
    SCREENSHARE_FINISHED: string;
    SCREENSHARE_FAILED: string;
    VIDEO_STREAM_ENDED: string;
    VIDEO_STREAM_QUALITY_CHANGED: string;
    CHANGE_LOG_OPENED: string;
    CHANGE_LOG_CLOSED: string;
    CHANGE_LOG_CTA_CLICKED: string;
    ACCOUNT_LINK_STEP: string;
    ACCOUNT_LINK_FAILED: string;
    CONNECTED_ACCOUNT_VIEWED: string;
    MEDIA_DEVICE_CHANGED: string;
    USER_SETTINGS_KEYBIND_UPDATED: string;
    USER_ATTRIBUTION_RECEIVED: string;
    DISPATCH_PATCH_STARTED: string;
    DISPATCH_PATCH_PAUSED: string;
    DISPATCH_PATCH_FAILED: string;
    DISPATCH_PATCH_VERIFICATION_FAILED: string;
    DISPATCH_PATCH_COMPLETE: string;
    DISPATCH_PATCH_CANCELLED: string;
    DISPATCH_APPLICATION_UNINSTALLED: string;
    STORE_DIRECTORY_VIEWED: string;
    STORE_DIRECTORY_BROWSE_VIEWED: string;
    STORE_DIRECTORY_FILTER_UPDATED: string;
    STORE_DIRECTORY_EXITED: string;
    STORE_DIRECTORY_HERO_VIEWED: string;
    STORE_DIRECTORY_CARD_INTERACTED: string;
    STORE_LISTING_VIEWED: string;
    STORE_LISTING_EXITED: string;
    STORE_LISTING_MEDIA_SCROLLED: string;
    STORE_BREADCRUMB_CLICK: string;
    LIBRARY_VIEWED: string;
    LIBRARY_INSTALL_INITIATED: string;
    LIBRARY_REPAIR_INITIATED: string;
    LIBRARY_UNINSTALL_INITIATED: string;
    LIBRARY_SCANNING_ENABLED: string;
    PROMOTION_VIEWED: string;
    APPLICATION_SETTINGS_UPDATED: string;
    NETWORKING_SYSTEM_METRICS: string;
    NETWORKING_PEER_METRICS: string;
    DYNAMIC_LINK_TYPE_SETTINGS: string;
    DYNAMIC_LINK_TYPE_LIBRARY: string;
    DYNAMIC_LINK_TYPE_STORE: string;
    DYNAMIC_LINK_TYPE_INVITE: string;
    MIC_TESTING_STARTED: string;
    MIC_TESTING_STOPPED: string;
    GIFT_CODE_SENT: string;
    GIFT_CODE_RESOLVED: string;
    GIFT_CODE_COPIED: string;
    SLASH_COMMAND_USED: string;
    SEARCH_RESULT_VIEWED: string;
    SEARCH_RESULT_SELECTED: string;
    SEARCH_RESULT_EXPANDED: string;
    SEARCH_RESULT_SORT_CHANGED: string;
    SEARCH_OPENED: string;
    SEARCH_STARTED: string;
    SEARCH_CLOSED: string;
    JUMP: string;
    GIF_FAVORITED: string;
    GIF_UNFAVORITED: string;
    GUILD_DISCOVERY_VIEWED: string;
    GUILD_DISCOVERY_GUILD_SELECTED: string;
    NEWS_EDITOR_VIEWED: string;
    NEWS_UPDATED: string;
    NEWS_LINK_COPIED: string;
    NEWS_LINK_SHARED: string;
}>, UserSearchWorkerMessageTypes: any, PublicReleaseChannels: Readonly<{
    CANARY: string;
    PTB: string;
    STABLE: string;
}>, UserFlags: Readonly<{
    STAFF: number;
    PARTNER: number;
    HYPESQUAD: number;
    BUG_HUNTER: number;
    HYPESQUAD_ONLINE_HOUSE_1: number;
    HYPESQUAD_ONLINE_HOUSE_2: number;
    HYPESQUAD_ONLINE_HOUSE_3: number;
    PREMIUM_EARLY_SUPPORTER: number;
    MFA_SMS: number;
    PREMIUM_PROMO_DISMISSED: number;
}>, ChannelNoticeTypes: any, DefaultCloudSyncConfiguration: Readonly<{
    STORAGE_MANIFEST: (e: any, t: any) => string;
    INSTALL_DIR: (e: any) => string;
    ROOT_PATTERN: string[];
    ROOT_STORAGE_PATH: (e: any, t: any) => string;
    ROOT_ID: string;
    ROOT_PLATFORMS: any;
}>, CHANNEL_NOTICE_SHOW_DELAY = 86400000, ChannelLayouts: Readonly<{
    NORMAL: string;
    MINIMUM: string;
    NO_CHAT: string;
    FULL_SCREEN: string;
}>, Layers: any, AuditLogActions: Readonly<{
    ALL: any;
    GUILD_UPDATE: number;
    CHANNEL_CREATE: number;
    CHANNEL_UPDATE: number;
    CHANNEL_DELETE: number;
    CHANNEL_OVERWRITE_CREATE: number;
    CHANNEL_OVERWRITE_UPDATE: number;
    CHANNEL_OVERWRITE_DELETE: number;
    MEMBER_KICK: number;
    MEMBER_PRUNE: number;
    MEMBER_BAN_ADD: number;
    MEMBER_BAN_REMOVE: number;
    MEMBER_UPDATE: number;
    MEMBER_ROLE_UPDATE: number;
    ROLE_CREATE: number;
    ROLE_UPDATE: number;
    ROLE_DELETE: number;
    INVITE_CREATE: number;
    INVITE_UPDATE: number;
    INVITE_DELETE: number;
    WEBHOOK_CREATE: number;
    WEBHOOK_UPDATE: number;
    WEBHOOK_DELETE: number;
    EMOJI_CREATE: number;
    EMOJI_UPDATE: number;
    EMOJI_DELETE: number;
    MESSAGE_DELETE: number;
}>, AuditLogActionTypes: any, AuditLogSubtargetTypes: Readonly<{
    USER: string;
    ROLE: string;
}>, AuditLogTargetTypes: any, AuditLogChangeKeys: Readonly<{
    NAME: string;
    DESCRIPTION: string;
    ICON_HASH: string;
    SPLASH_HASH: string;
    BANNER_HASH: string;
    OWNER_ID: string;
    REGION: string;
    AFK_CHANNEL_ID: string;
    AFK_TIMEOUT: string;
    SYSTEM_CHANNEL_ID: string;
    MFA_LEVEL: string;
    WIDGET_ENABLED: string;
    WIDGET_CHANNEL_ID: string;
    VERIFICATION_LEVEL: string;
    EXPLICIT_CONTENT_FILTER: string;
    DEFAULT_MESSAGE_NOTIFICATIONS: string;
    VANITY_URL_CODE: string;
    POSITION: string;
    TOPIC: string;
    TYPE: string;
    BITRATE: string;
    PERMISSION_OVERWRITES: string;
    ROLES_ADD: string;
    ROLES_REMOVE: string;
    NICK: string;
    DEAF: string;
    MUTE: string;
    PERMISSIONS: string;
    COLOR: string;
    HOIST: string;
    MENTIONABLE: string;
    CODE: string;
    CHANNEL_ID: string;
    INVITER_ID: string;
    MAX_USES: string;
    USES: string;
    MAX_AGE: string;
    TEMPORARY: string;
    APPLICATION_ID: string;
    AVATAR_HASH: string;
    ID: string;
    PERMISSIONS_GRANTED: string;
    PERMISSIONS_DENIED: string;
    REASON: string;
    PRUNE_DELETE_DAYS: string;
    NSFW: string;
    RATE_LIMIT_PER_USER: string;
}>, AUDIT_LOG_PAGE_LIMIT = 50, UserRequiredActions: any, VerificationTypes: Readonly<{
    CAPTCHA: string;
    EMAIL_OR_PHONE: string;
    PHONE: string;
}>, MAX_REASON_LENGTH = 512, MouseButtons: Readonly<{
    PRIMARY: number;
    SECONDARY: number;
    WHEEL: number;
    BACK: number;
    FORWARD: number;
}>, KeyboardKeys: Readonly<{
    BACKSPACE: number;
    TAB: number;
    ENTER: number;
    ESCAPE: number;
    SPACE: number;
    ARROW_LEFT: number;
    ARROW_UP: number;
    ARROW_RIGHT: number;
    ARROW_DOWN: number;
    DIGIT_0: number;
    DIGIT_1: number;
    DIGIT_2: number;
    DIGIT_3: number;
    DIGIT_4: number;
    DIGIT_5: number;
    DIGIT_6: number;
    DIGIT_7: number;
    DIGIT_8: number;
    DIGIT_9: number;
    N: number;
    P: number;
}>, EnableAccessibility: boolean, PictureInPicturePositions: Readonly<{
    TOP_LEFT: string;
    TOP_RIGHT: string;
    BOTTOM_LEFT: string;
    BOTTOM_RIGHT: string;
}>, PictureInPictureComponents: Readonly<{
    VIDEO: string;
}>, SCREENSHARE_CHROME_EXTENSION_ID = "lcbhdgefieegnkbopmgklhlpjjdgmbog", ScreenshareChromeExtensionCommands: Readonly<{
    SCREENSHARE: string;
}>, ScreenshareChromeExtensionResponseTypes: Readonly<{
    SCREENSHARE_START_SUCCESS: string;
    SCREENSHARE_START_CANCEL: string;
    UNKNOWN_COMMAND: string;
}>, USER_STATUS_TOOLTIP_DELAY = 300, ChannelTextAreaIntegrationTypes: Readonly<{
    GIF: string;
}>;
export declare const ChannelTextAreaIntegrations: Readonly<{
    GIPHY: {
        type: any;
        command: string;
        title: string;
    };
    TENOR: {
        type: any;
        command: string;
        title: string;
    };
}>, ActivityJoinRequestStates: any, MEDIA_PROXY_SIZES: number[], HelpdeskArticles: Readonly<{
    ENABLE_MIC_FIREFOX: string;
    PUSH_TO_TALK_ADMINISTRATOR_MODE: string;
    ENABLE_MIC_CHROME: string;
    PERMISSIONS_TUTORIAL: string;
    VOICE_CONNECTION_ERRORS: string;
    NO_INPUT_DETECTED: string;
    OVERLAY_INTRODUCTION: string;
    PERMISSIONS_LOCKOUT: string;
    SETTING_UP_TWO_FACTOR: string;
    FRIEND_SYNC_PRIVACY: string;
    WEBHOOKS_INTRODUCTION: string;
    QUICK_SWITCHER_TUTORIAL: string;
    SEARCH_INDEXING: string;
    USING_SEARCH: string;
    RICH_PRESENCE_INTRODUCTION: string;
    CORRUPT_INSTALLATION: string;
    SPOTIFY_AUTO_PAUSED: string;
    SPOTIFY_CONNECTION: string;
    SPELLCHECK: string;
    INVALID_INVITES: string;
    GDPR_ACCOUNT_DELETE: string;
    GDPR_ACCOUNT_DISABLE: string;
    GDPR_REQUEST_DATA: string;
    DATA_PRIVACY_CONTROLS: string;
    NEARBY_FRIENDS: string;
    APPLICATION_STORE_OVERVIEW: string;
    APPLICATION_STORE_EARLY_ACCESS: string;
    GIFTING: string;
}>, DevHelpdeskArticles: Readonly<{
    SERVER_BANNERS: string;
}>, AccountModalSteps: any, AccountModalTypes: any, EmbedTypes: Readonly<{
    IMAGE: string;
    VIDEO: string;
    LINK: string;
    ARTICLE: string;
    TWEET: string;
    RICH: string;
    GIFV: string;
    APPLICATION_NEWS: string;
}>, GameNewsFlags: Readonly<{
    PATCH_NOTES: number;
    PROMOTION: number;
}>, FeedCarouselItemTypes: Readonly<{
    APPLICATION_NEWS: string;
    PROMOTION: string;
}>, SPOTIFY_APP_PROTOCOL = "spotify";
export declare const PURGE_MEMORY_TIMEOUT = 300000, INVITE_ENDPOINT = "https://discord.gg", YOUTUBE_EMBED_URL: (e: any) => string, YOUTUBE_PREVIEW_URL: (e: any) => string, YOUTUBE_EXTERNAL_URL: (e: any) => string, LibraryApplicationFlags: Readonly<{
    HIDDEN: number;
    PRIVATE: number;
    OVERLAY_DISABLED: number;
    ENTITLED: number;
    PREMIUM: number;
}>, CloudSyncStateTypes: any, CloudSyncResultTypes: any, Distributors: Readonly<{
    DISCORD: string;
    STEAM: string;
    TWITCH: string;
    UPLAY: string;
    BATTLENET: string;
    ORIGIN: string;
    GOG: string;
    EPIC: string;
}>;
export declare const DistributorNames: any, MAX_VIDEO_WIDTH = 3840, MAX_VIDEO_HEIGHT = 2160, Consents: Readonly<{
    USAGE_STATISTICS: string;
    PERSONALIZATION: string;
}>, FriendSourceFlagKeys: Readonly<{
    ALL: string;
    FRIENDS: string;
    GUILDS: string;
}>, REQUEST_DATA_LIMIT_DAYS = 30, LobbyTypes: Readonly<{
    PRIVATE: number;
    PUBLIC: number;
}>, LobbyErrors: Readonly<{
    NO_ERROR: number;
    UNKNOWN_ERROR: number;
    SERVICE_UNAVAILABLE: number;
    NOT_FOUND: number;
    INVALID_SECRET: number;
    FULL: number;
    LOBBY_LIMIT_REACHED: number;
    ALREADY_CONNECTING: number;
}>, AppContext: any;
export declare const NearbyErrors: Readonly<{
    MICROPHONE_ERROR: number;
    BLUETOOTH_ERROR: number;
}>, NearbyTypes: Readonly<{
    USER: string;
}>, CURRENT_APP_CONTEXT: any, SPOTIFY_HOSTNAMES: string[];
export declare const SpotifyEndpoints: Readonly<{
    PROFILE: string;
    NOTIFICATIONS_PLAYER: string;
    PLAYER: string;
    PLAYER_DEVICES: string;
    PLAYER_PLAY: string;
    PLAYER_PAUSE: string;
    PLAYER_REPEAT: string;
    WEB_OPEN: (e: any, t: any) => string;
    EMBED: (e: any) => string;
    PLAYER_OPEN: (e: any, t: any) => string;
    PREMIUM_SITE: string;
    INSTALL_ATTRIBUTION: (e: any) => string;
    IOS_APP_STORE: string;
}>, INSTANT_INVITE_BASE_URL = "discordapp.com/invite", GIFT_CODE_BASE_URL = "discordapp.com/gifts", DispatchApplicationStates: Readonly<{
    COMPLETE: string;
    TRANSITION: string;
}>, DispatchApplicationStages: Readonly<{
    QUEUED: string;
    PLANNING: string;
    ALLOCATING_DISK: string;
    PATCHING: string;
    FINALIZING: string;
    PAUSING: string;
    VERIFYING: string;
    REPAIRING: string;
    POST_INSTALL_SCRIPTS: string;
    UNINSTALLING: string;
}>, LocalDispatchApplicationStates: Readonly<{
    INSTALL_REQUIRED: string;
    INSTALLING: string;
    UP_TO_DATE: string;
    UPDATE_REQUIRED: string;
    UPDATING: string;
    REPAIRING: string;
    UNINSTALLING: string;
}>, LibraryApplicationActions: Readonly<{
    PLAY: string;
    INSTALL: string;
    UPDATE: string;
    PAUSE: string;
    MOVE_UP: string;
    RESUME: string;
}>, ProgressBarIDs: Readonly<{
    DISPATCH_APPLICATION_PROGRESS: string;
}>, GameTableListKeys: Readonly<{
    NAME: string;
    PLATFORM: string;
    ACTIONS: string;
    LAST_PLAYED: string;
}>, TableSortDirections: Readonly<{
    ASCENDING: string;
    DESCENDING: string;
}>, OperatingSystems: Readonly<{
    WINDOWS: string;
    MACOS: string;
    LINUX: string;
}>, EntitlementTypes: Readonly<{
    PURCHASE: number;
    PREMIUM_SUBSCRIPTION: number;
    DEVELOPER_GIFT: number;
    TEST_MODE_PURCHASE: number;
    FREE_PURCHASE: number;
    USER_GIFT: number;
}>, ContentRatingAgencies: Readonly<{
    ESRB: string;
    PEGI: string;
}>, SKUTypes: Readonly<{
    GAME: number;
    DLC: number;
    CONSUMABLE: number;
    BUNDLE: number;
    SUBSCRIPTION: number;
}>, SKUAccessTypes: Readonly<{
    FULL: number;
    EARLY_ACCESS: number;
    VIP_ACCESS: number;
}>, SKUFlags: Readonly<{
    PREMIUM_PURCHASE: number;
    HAS_FREE_PREMIUM_CONTENT: number;
    AVAILABLE: number;
    PREMIUM_AND_DISTRIBUTION: number;
}>, STORE_DIRECTORY_LAYOUT_ID = "555552588917899315", STORE_DIRECTORY_LAYOUT_ID_QUERY_OVERRIDE = "store_directory_layout_id", StoreDirectoryExperimentLayoutIds: {
    TREATMENT_1: string;
    TREATMENT_2: string;
    TREATMENT_3: string;
}, StoreDirectoryTileTypes: Readonly<{
    BOX_ART: string;
    PERK: string;
}>, DirectoryLocations: Readonly<{
    HOME: string;
    BROWSE: string;
}>, StoreApplicationGenresFilter: any, StoreApplicationSort: Readonly<{
    NEW_RELEASES: string;
    ALPHABETICAL: string;
    REVERSE_ALPHABETICAL: string;
    ID: string;
}>, BuildPlatformTypes: Readonly<{
    WIN32: string;
    WIN64: string;
    MACOS: string;
    LINUX: string;
}>, PAYPAL_URL = "https://www.paypal.com", COUNTRIES_WITHOUT_POSTAL_CODES: string[], HypeSquadHouses: any, RANDOM_HYPESQUAD_HOUSE = "RANDOM_HYPESQUAD_HOUSE", KeyboardDeviceTypes: Readonly<{
    KEYBOARD_KEY: number;
    MOUSE_BUTTON: number;
    KEYBOARD_MODIFIER_KEY: number;
    GAMEPAD_BUTTON: number;
}>, LinuxKeyToCode: Readonly<{
    esc: number;
    f1: number;
    f2: number;
    f3: number;
    f4: number;
    f5: number;
    f6: number;
    f7: number;
    f8: number;
    f9: number;
    f10: number;
    f11: number;
    f12: number;
    f14: number;
    f15: number;
    f16: number;
    "`": number;
    1: number;
    2: number;
    3: number;
    4: number;
    5: number;
    6: number;
    7: number;
    8: number;
    9: number;
    0: number;
    "-": number;
    "=": number;
    backspace: number;
    tab: number;
    q: number;
    w: number;
    e: number;
    r: number;
    t: number;
    y: number;
    u: number;
    i: number;
    o: number;
    p: number;
    "[": number;
    "]": number;
    "\\": number;
    "caps lock": number;
    a: number;
    s: number;
    d: number;
    f: number;
    g: number;
    h: number;
    j: number;
    k: number;
    l: number;
    ";": number;
    "'": number;
    enter: number;
    "left shift": number;
    z: number;
    x: number;
    c: number;
    v: number;
    b: number;
    n: number;
    m: number;
    ",": number;
    ".": number;
    "/": number;
    "right shift": number;
    "left ctrl": number;
    "left alt": number;
    "left meta": number;
    space: number;
    "right meta": number;
    "right alt": number;
    "right ctrl": number;
    menu: number;
    "num lock": number;
    "numpad =": number;
    "numpad /": number;
    "numpad *": number;
    "numpad 7": number;
    "numpad 8": number;
    "numpad 9": number;
    "numpad -": number;
    "numpad 4": number;
    "numpad 5": number;
    "numpad 6": number;
    "numpad +": number;
    "numpad 1": number;
    "numpad 2": number;
    "numpad 3": number;
    "numpad enter": number;
    "numpad 0": number;
    "numpad .": number;
    home: number;
    "page up": number;
    end: number;
    "page down": number;
    insert: number;
    delete: number;
    left: number;
    right: number;
    down: number;
    up: number;
    sleep: number;
    back: number;
    forward: number;
    "home key": number;
    favorites: number;
    email: number;
    play: number;
    stop: number;
    "vol down": number;
    "vol up": number;
    "track back": number;
    "track skip": number;
}>, MacosKeyToCode: Readonly<{
    a: number;
    s: number;
    d: number;
    f: number;
    h: number;
    g: number;
    z: number;
    x: number;
    c: number;
    v: number;
    b: number;
    q: number;
    w: number;
    e: number;
    r: number;
    y: number;
    t: number;
    1: number;
    2: number;
    3: number;
    4: number;
    6: number;
    5: number;
    "=": number;
    9: number;
    7: number;
    "-": number;
    8: number;
    0: number;
    "]": number;
    o: number;
    u: number;
    "[": number;
    i: number;
    p: number;
    l: number;
    j: number;
    "'": number;
    k: number;
    ";": number;
    "\\": number;
    ",": number;
    "/": number;
    n: number;
    m: number;
    ".": number;
    "`": number;
    "numpad .": number;
    "numpad *": number;
    "numpad +": number;
    "numpad clear": number;
    "numpad /": number;
    "numpad enter": number;
    "numpad -": number;
    "numpad =": number;
    "numpad 0": number;
    "numpad 1": number;
    "numpad 2": number;
    "numpad 3": number;
    "numpad 4": number;
    "numpad 5": number;
    "numpad 6": number;
    "numpad 7": number;
    "numpad 8": number;
    "numpad 9": number;
    enter: number;
    tab: number;
    space: number;
    backspace: number;
    esc: number;
    meta: number;
    shift: number;
    "caps lock": number;
    alt: number;
    ctrl: number;
    "right shift": number;
    "right alt": number;
    "right ctrl": number;
    "right meta": number;
    f17: number;
    f18: number;
    f19: number;
    f20: number;
    f5: number;
    f6: number;
    f7: number;
    f3: number;
    f8: number;
    f9: number;
    f11: number;
    f13: number;
    f16: number;
    f14: number;
    f10: number;
    f12: number;
    f15: number;
    home: number;
    "page up": number;
    del: number;
    f4: number;
    end: number;
    f2: number;
    "page down": number;
    f1: number;
    left: number;
    right: number;
    down: number;
    up: number;
}>, WindowsKeyToCode: Readonly<{
    a: number;
    s: number;
    d: number;
    f: number;
    h: number;
    g: number;
    z: number;
    x: number;
    c: number;
    v: number;
    b: number;
    q: number;
    w: number;
    e: number;
    r: number;
    y: number;
    t: number;
    1: number;
    2: number;
    3: number;
    4: number;
    6: number;
    5: number;
    "=": number;
    9: number;
    7: number;
    "-": number;
    8: number;
    0: number;
    "]": number;
    o: number;
    u: number;
    "[": number;
    i: number;
    p: number;
    l: number;
    j: number;
    k: number;
    ";": number;
    ",": number;
    "/": number;
    n: number;
    m: number;
    ".": number;
    "numpad .": number;
    "numpad *": number;
    "numpad +": number;
    "numpad clear": number;
    "numpad /": number;
    "numpad -": number;
    "numpad =": number;
    "numpad 0": number;
    "numpad 1": number;
    "numpad 2": number;
    "numpad 3": number;
    "numpad 4": number;
    "numpad 5": number;
    "numpad 6": number;
    "numpad 7": number;
    "numpad 8": number;
    "numpad 9": number;
    enter: number;
    tab: number;
    space: number;
    backspace: number;
    esc: number;
    meta: number;
    shift: number;
    "caps lock": number;
    alt: number;
    ctrl: number;
    "right shift": number;
    "right alt": number;
    "right ctrl": number;
    "right meta": number;
    f17: number;
    f18: number;
    f19: number;
    f5: number;
    f6: number;
    f7: number;
    f3: number;
    f8: number;
    f9: number;
    f11: number;
    f13: number;
    f16: number;
    f14: number;
    f10: number;
    f12: number;
    f15: number;
    home: number;
    "page up": number;
    del: number;
    f4: number;
    end: number;
    f2: number;
    "page down": number;
    f1: number;
    left: number;
    right: number;
    down: number;
    up: number;
    insert: number;
    break: number;
    "scroll lock": number;
    "print screen": number;
    rewind: number;
    play: number;
    "fast forward": number;
    "`": number;
    "\\": number;
    "'": number;
}>, KeyboardEnvs: Readonly<{
    WINDOWS: number;
    MACOS: number;
    LINUX: number;
    BROWSER: number;
}>, MessageRestrictionTypes: any, ReviewAggregators: Readonly<{
    METACRITIC: number;
}>, MESSAGE_GROUP_INTERVAL = 420000, CarouselMediaTypes: Readonly<{
    IMG: number;
    YOUTUBE_VIDEO: number;
    VIDEO: number;
}>, StoreRecommendationTypes: Readonly<{
    NOW_PLAYING: string;
    RECENTLY_PLAYED: string;
    EVER_PLAYED: string;
    FLAVOR_TEXT: string;
    METACRITIC_SCORE: string;
    RECENT_RELEASE_DATE: string;
    RELEASE_DATE: string;
    EARLY_ACCESS: string;
    HAS_FREE_PREMIUM_CONTENT: string;
}>, PromotionTypes: Readonly<{
    GENERAL: string;
    GAME: string;
}>, PROMOTION_ASSET_HEIGHT = 388, PROMOTION_ASSET_WIDTH = 945, PromotionAckTypes: Readonly<{
    CLICK: string;
    IMPRESSION: string;
}>, OverlayNotificationPriorities: Readonly<{
    NORMAL: number;
    HIGH: number;
    URGENT: number;
}>, ConnectedDeviceType: any, ConnectedDevicePreference: any, ViewHistoryKeys: Readonly<{
    APPLICATION_LIBRARY_BADGE: string;
    APPLICATION_LIBRARY_PREMIUM: string;
    SERVER_DISCOVERY_BADGE: string;
}>, InAppNotificationTypes: Readonly<{
    MESSAGE: string;
    SERVER_DOWN_ALERT: string;
}>, GIFPickerResultTypes: Readonly<{
    TRENDING_GIFS: string;
    FAVORITES: string;
    TRENDING_CATEGORY: string;
    SEARCH: string;
    SEARCH_SUGGESTION: string;
}>, GIFTABLE_CURRENCIES: Set<any>, GIFProviders: {
    GIPHY: string;
    TENOR: string;
}, TenorFormats: {
    GIF: string;
    MP4: string;
    MEDIUMGIF: string;
    TINYGIF: string;
    NANOGIF: string;
    LOOPEDMP4: string;
    TINYMP4: string;
    NANOMP4: string;
    WEBM: string;
    TINYWEBM: string;
    NANOWEBM: string;
}, GIPHYFormats: {
    FIXED_HEIGHT_GIF: string;
    FIXED_HEIGHT_MP4: string;
    FIXED_HEIGHT_SMALL_GIF: string;
    FIXED_HEIGHT_SMALL_MP4: string;
    FIXED_WIDTH_GIF: string;
    FIXED_WIDTH_MP4: string;
    FIXED_WIDTH_SMALL_GIF: string;
    FIXED_WIDTH_SMALL_MP4: string;
    DOWNSIZED_GIF: string;
    DOWNSIZED_LARGE_GIF: string;
    DOWNSIZED_MEDIUM_GIF: string;
    DOWNSIZED_SMALL_MP4: string;
    ORIGINAL_GIF: string;
    ORIGINAL_MP4: string;
}, GIFResultFormat: any, FeedLayouts: any, FeedCardTypes: any, SpoilerRenderSetting: any, CustomDiscordApplicationId = "530820671283003422", UNAMBIGUOUS_CHARACTERS = "abcdefghjkmnpqrstuvwxyzABCDEFGHJKMNPQRSTUVWXYZ23456789", MAX_TIMEOUT_MS = 2147483647, PREMIUM_ROUTE_HASH = "#premium";
export declare const PERK_TILES: ({
    image: string;
    video: string;
    skuId: string;
    name: string;
    tagline: string;
} | {
    image: any;
    skuId: any;
    name: string;
    tagline: string;
    video?: undefined;
})[];
